### ISSUE TITLE
RPM Failed

### ISSUE THREAD

**Issue by djhanz** [maybegreat48/External#1]
Seems like RPM fails at get_program_by_hash(joaat_t hash)?

Btw nice project, this is real smart.

**Comment by maybegreat48** [comment]
Try to inject in singleplayer as its more stable there for some reason, model spawn is still broken (it spawns now but you get kicked out of vehicle). Will fix all this when I have the time

**Comment by djhanz** [comment]
Doesn't seem to fix anything, well i'll try to take a deeper look otherwise i'll just wait for you to fix when u got time.

Thank you man.

**Comment by maybegreat48** [comment]
Is this still an issue?

**Comment by Vali0004** [comment]
I tested it myself, still an issue in story and online.
I was also dying at RPM, looking at the callstack it seemed to be get_program_by_hash on line 74

**Comment by Vali0004** [comment]
Fixed it! At least, the part that crashed. You set the RPM as a uint32_t, but the variable was a uint64_t
Changing it to a uint64_t on line 70 fixed it.

**Comment by maybegreat48** [comment]
Thanks, fixed it!
Are there any other issues?

**Comment by Vali0004** [comment]
Pick script has some, I changed some and fixed it. Erm, other than that? Not really.
I'll create a repo with everything that I'm doing. I'm currently doing everything in a more dynamic way.
I'm also implementing ImGui and creating a UI.

**Comment by Vali0004** [comment]
`void script_loader::pick_script() {
		// https://stackoverflow.com/a/49652087
		OPENFILENAME ofn = { 0 };
		// Initialize remaining fields of OPENFILENAME structure
		ofn.lStructSize = sizeof(ofn);
		ofn.hwndOwner = FindWindowA(nullptr, "External");
		ofn.lpstrFile = m_file_name;
		ofn.nMaxFile = sizeof(m_file_name);
		ofn.lpstrFilter = L"All\0*.*\0Text\0*.TXT\0";
		ofn.nFilterIndex = 1;
		ofn.lpstrFileTitle = NULL;
		ofn.nMaxFileTitle = 0;
		ofn.lpstrInitialDir = NULL;
		ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

		if (GetOpenFileName(&ofn) != TRUE) {
			exit(0);
		}
	}`

**Comment by djhanz** [comment]
Sorry been busy, can confirm the latest commit fixes this issue.
