### ISSUE TITLE
Crossmaps appears to be non-functional as of GTA V 1.59

### ISSUE THREAD

**Issue by wizard00000** [maybegreat48/External#2]
line 75 (crossmap #67) and one of the crossmaps in the 6100 area prevent External from loading.
Assuming the issue is due to outdated crossmaps for the new update but the crossmaps are the same as yim menu which has worked fine for me when testing.

**Comment by maybegreat48** [comment]
Will be fixed in next commit. The native MISC::IS_BIT_SET was completely removed this update. External requires all the natives to be found whereas YimMenu (and other BigBaseV2 based menus) do not
